name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install

      - name: Start the application
        run: npm start &

      - name: Run Cypress tests
        run: npm run cypress:run

  deploy:
    runs-on: ubuntu-latest
    needs: [unit-tests, e2e-tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure Git
        run: |
          git config --global user.email "remi_annat@hotmail.com"
          git config --global user.name "rannat69"
      - name: Install dependencies
        run: npm install
      - name: Build the application
        run: npm run build
      - name: Deploy to github pages
        uses: rannat69/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }} # Use the secret
            publish_dir: ./build
